stages:
  - checks

test:
  stage: checks
  tags:
    - aave-build-runner
  before_script:
    - docker-compose -f docker-compose.test.yml build
  script:
    - docker-compose -f docker-compose.test.yml run contracts-env npm run ci:test
  after_script:
    - docker-compose -f docker-compose.test.yml run contracts-env npm run ci:clean
    - docker-compose -f docker-compose.test.yml down

deploy-mainnet-fork:
  stage: checks
  tags:
    - aave-build-runner
  before_script:
    - docker-compose build
  script:
    - docker-compose run contracts-env npm aave:fork:main
  after_script:
    - docker-compose -f docker-compose.test.yml run contracts-env npm run ci:clean
    - docker-compose -f docker-compose.test.yml down
