stages:
  - test

test:
  stage: test
  tags:
    - aave-build-runner
  before_script:
    - docker-compose -f docker-compose.test.yml build
  script:
    - docker-compose -f docker-compose.test.yml run contracts-env npm run ci:test
  after_script:
    - docker-compose -f docker-compose.test.yml run contracts-env npm run ci:clean
    - docker-compose -f docker-compose.test.yml down

certora-test:
  stage: test
  image: python:latest
  before_script:
    - apt-get update || apt-get update
    - apt-get install -y software-properties-common
    - pip3 install certora-cli-beta==0.4.1
    - wget https://github.com/ethereum/solidity/releases/download/v0.6.12/solc-static-linux
    - chmod +x solc-static-linux
    - mv solc-static-linux /usr/bin/solc
    - export PATH=$PATH:/usr/bin/solc/solc-static-linux
  script:
    - certoraRun specs/harness/StableDebtTokenHarness.sol:StableDebtTokenHarness --verify StableDebtTokenHarness:specs/StableDebtToken.spec --settings -assumeUnwindCond --cache StableDebtToken --staging
    - certoraRun specs/harness/UserConfigurationHarness.sol --verify UserConfigurationHarness:specs/UserConfiguration.spec --settings -useBitVectorTheory --staging
    - certoraRun contracts/tokenization/VariableDebtToken.sol:VariableDebtToken specs/harness/LendingPoolHarnessForVariableDebtToken.sol --solc_args '--optimize' --link VariableDebtToken:POOL=LendingPoolHarnessForVariableDebtToken --verify VariableDebtToken:specs/VariableDebtToken.spec --settings -assumeUnwindCond,-useNonLinearArithmetic,-b=4 --cache VariableDebtToken --staging

