version: "3.5"

services:
  contracts-env:
    build:
      context: ./
    working_dir: /src
    command: npm run run-env
    depends_on:
      - ganache
    volumes:
      - ./:/src

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: [
      "ganache-cli",
      "--gasLimit", "10000000",
      "--mnemonic", "frame post antenna before valid claw crunch clap travel buyer inch act",
      "--hardfork", "istanbul"
    ]